Change file ending to .featmat add option to just generate commands

diff --git a/scripts/cfmsinfer-build b/scripts/cfmsinfer-build
--- a/scripts/cfmsinfer-build
+++ b/scripts/cfmsinfer-build
@@ -10,9 +10,11 @@ if [ ! -n $FEAT_FILE ];then
 fi
 
 if [ -n "$EXP_PREFIX" ]; then
-  OUTPUT_FILE=feature_matrix/${EXP_PREFIX}_feature_matrix.csv
+  OUTPUT_FILE=feature_matrix/${EXP_PREFIX}.featmat
 else
-  OUTPUT_FILE=feature_matrix/feature_matrix.csv
+   echo "Please provide EXP_PREFIX in config file"
+   exit 1 
+
 fi
 
 rm -f logs/log_build_featmat 
@@ -28,21 +30,24 @@ else
   echo "python $PCM_DIR/protein_complex_maps/features/build_feature_matrix.py --input_pairs_list $FEAT_FILE --store_interval $STORE_INTERVAL --output_file $OUTPUT_FILE --sep ','" > records/record_build_featmat.sh
 fi
 
-bash records/record_build_featmat.sh > logs/log_build_featmat 2> logs/error_build_featmat
 
+if [ $GEN_COMMANDS_ONLY != "T" ];then
 
-# Remove empty error log
-find "logs" -maxdepth 1 -name "error_build_featmat" -empty -delete
-
-if [ -f logs/error_build_featmat ]; then
-  ls logs/error_build_featmat
-  echo -e "\e[91mError while building feature matrix\e[39m"
-  echo -e "\e[91mSee log at logs/error_build_featmat\e[39m"
-  exit 1
-else
-  echo -e "\e[35mFeature matrix built without errors ($OUTPUT_FILE)\e[39m"
-
-fi 
-
-
+  bash records/record_build_featmat.sh > logs/log_build_featmat 2> logs/error_build_featmat
+  
+  
+  # Remove empty error log
+  find "logs" -maxdepth 1 -name "error_build_featmat" -empty -delete
+  
+  if [ -f logs/error_build_featmat ]; then
+    ls logs/error_build_featmat
+    echo -e "\e[91mError while building feature matrix\e[39m"
+    echo -e "\e[91mSee log at logs/error_build_featmat\e[39m"
+    exit 1
+  else
+    echo -e "\e[35mFeature matrix built without errors ($OUTPUT_FILE)\e[39m"
+  
+  fi 
+fi    
+  
 
diff --git a/scripts/cfmsinfer-gold b/scripts/cfmsinfer-gold
--- a/scripts/cfmsinfer-gold
+++ b/scripts/cfmsinfer-gold
@@ -48,7 +48,7 @@ fi
 if [ "$MAKE_NEGATIVES_FROM_OBSERVED" = "T" ]
 then
   # Get all ID pairs from the feature matrix (remove header with tail)
-  echo "awk -F',' '{print \$1}' feature_matrix/${EXP_PREFIX}_feature_matrix.csv |  tail -n +2 > gold_standards/identifiers_infeatmat.txt" >> records/record_gold_standard.sh
+  echo "awk -F',' '{print \$1}' feature_matrix/${EXP_PREFIX}.featmat |  tail -n +2 > gold_standards/identifiers_infeatmat.txt" >> records/record_gold_standard.sh
   
   # Remove any interactions that are in the positive set
   echo "grep -vFf gold_standards/pos_train.txt gold_standards/identifiers_infeatmat.txt | grep -vFf gold_standards/pos_test.txt> gold_standards/neg_pool.txt" >> records/record_gold_standard.sh
@@ -76,23 +76,25 @@ fi
 rm -f logs/log_gold_standard
 rm -f logs/error_gold_standard
 
-bash records/record_gold_standard.sh > logs/log_gold_standard 2> logs/error_gold_standard 
- 
-# Remove empty error log
-find "logs" -maxdepth 1 -name "error_gold_standard" -empty -delete
+if [ $GEN_COMMANDS_ONLY != "T" ];then
 
-if [ -f logs/error_gold_standard ]; then
-  ls logs/error_gold_standard
-  echo -e "\e[91mError while building feature matrix\e[39m"
-  echo -e "\e[91mSee output log at logs/log_gold_standard\e[39m"
-  echo -e "\e[91mSee error log at logs/error_gold_standard\e[39m"
-
-  exit 1
-else
-  echo -e "\e[35mGold standard files made without errors (gold_standards/neg_train.txt, gold_standards/neg_test.txt, gold_standard/pos_train.txt, gold_standards/pos_test.txt)\e[39m"
-
+  bash records/record_gold_standard.sh > logs/log_gold_standard 2> logs/error_gold_standard 
+   
+  # Remove empty error log
+  find "logs" -maxdepth 1 -name "error_gold_standard" -empty -delete
+  
+  if [ -f logs/error_gold_standard ]; then
+    ls logs/error_gold_standard
+    echo -e "\e[91mError while building feature matrix\e[39m"
+    echo -e "\e[91mSee output log at logs/log_gold_standard\e[39m"
+    echo -e "\e[91mSee error log at logs/error_gold_standard\e[39m"
+  
+    exit 1
+  else
+    echo -e "\e[35mGold standard files made without errors (gold_standards/neg_train.txt, gold_standards/neg_test.txt, gold_standard/pos_train.txt, gold_standards/pos_test.txt)\e[39m"
+  
+  fi
 fi
-
 
 
 
diff --git a/scripts/cfmsinfer-label b/scripts/cfmsinfer-label
--- a/scripts/cfmsinfer-label
+++ b/scripts/cfmsinfer-label
@@ -5,8 +5,8 @@ export PYTHONPATH=$PCM_DIR
 
 echo -e "\e[32mLabel feature matrix\e[39m"
 
-if [ ! -f feature_matrix/${EXP_PREFIX}_feature_matrix.csv ];then
-   echo -e "\e[32m Expected feature matrix feature_matrix/${EXP_PREFIX}_feature_matrix.csv not found\e[39m"
+if [ ! -f feature_matrix/${EXP_PREFIX}.featmat ];then
+   echo -e "\e[32m Expected feature matrix feature_matrix/${EXP_PREFIX}.featmat not found\e[39m"
    exit 1
 fi
 
@@ -19,28 +19,29 @@ fi
   
 
 # Adding label of gold standard training complexes
-echo "python $PCM_DIR/protein_complex_maps/features/add_label.py --input_feature_matrix feature_matrix/${EXP_PREFIX}_feature_matrix.csv --input_positives gold_standards/pos_train.txt --input_negatives gold_standards/neg_train.txt --sep , --ppi_sep ' ' --id_column ID --output_file feature_matrix/${EXP_PREFIX}_feature_matrix.labeled --fillna 0 --id_sep ' '" > records/record_label_featmat.sh  
+echo "python $PCM_DIR/protein_complex_maps/features/add_label.py --input_feature_matrix feature_matrix/${EXP_PREFIX}.featmat --input_positives gold_standards/pos_train.txt --input_negatives gold_standards/neg_train.txt --sep , --ppi_sep ' ' --id_column ID --output_file feature_matrix/${EXP_PREFIX}_feature_matrix.labeled --fillna 0 --id_sep ' '" > records/record_label_featmat.sh  
 
 # Get training labeled interactions
 # Separate this part out
 # Need to format for tpot as well by replacing ID space with comma
 echo "grep -v ",0.0\$" feature_matrix/${EXP_PREFIX}_feature_matrix.labeled > feature_matrix/${EXP_PREFIX}_feature_matrix.labeled1" >> records/record_label_featmat.sh  
  
-bash records/record_label_featmat.sh  > logs/log_label_featmat 2> logs/error_label_featmat
-
-
-# Remove empty error log
-find "logs" -maxdepth 1 -name "error_label_featmat" -empty -delete
-
-if [ -f logs/error_label_featmat ]; then
-  ls logs/error_label_featmat
-  echo -e "\e[91mError while building feature matrix\e[39m"
-  echo -e "\e[91mSee stdout log at logs/log_label_featmat\e[39m"
-  echo -e "\e[91mSee error log at logs/error_label_featmat\e[39m"
-  exit 1
-else
-  echo -e "\e[35mFeature matrix labeled without errors (${EXP_PREFIX}_feature_matrix.labeled)\e[39m"
-
-fi 
-
+if [ $GEN_COMMANDS_ONLY != "T" ];then
+  bash records/record_label_featmat.sh  > logs/log_label_featmat 2> logs/error_label_featmat
+  
+  
+  # Remove empty error log
+  find "logs" -maxdepth 1 -name "error_label_featmat" -empty -delete
+  
+  if [ -f logs/error_label_featmat ]; then
+    ls logs/error_label_featmat
+    echo -e "\e[91mError while building feature matrix\e[39m"
+    echo -e "\e[91mSee stdout log at logs/log_label_featmat\e[39m"
+    echo -e "\e[91mSee error log at logs/error_label_featmat\e[39m"
+    exit 1
+  else
+    echo -e "\e[35mFeature matrix labeled without errors (${EXP_PREFIX}_feature_matrix.labeled)\e[39m"
+  
+  fi 
+fi
 
diff --git a/scripts/cfmsinfer-scan b/scripts/cfmsinfer-scan
--- a/scripts/cfmsinfer-scan
+++ b/scripts/cfmsinfer-scan
@@ -17,35 +17,39 @@ else
 
 fi
 
-#bash records/record_scan.sh > logs/log_scan 2> logs/error_scan
+if [ $GEN_COMMANDS_ONLY != "T" ];then
 
-# Temp directories are very large
-rm -r training/*tmp
+  bash records/record_scan.sh > logs/log_scan 2> logs/error_scan
+  
+  # Temp directories are very large
+  rm -r training/*tmp
+  
+  # Remove empty error files (meaning no error)
+  # Parallel returns an empty stderr by default
+  find "logs" -maxdepth 1 -name "error_scan" -empty -delete
+  
+  #Look for any errors and report. Error log is cleared out at each run so any new errors are from current run
+  
+  # Cat to wc -l, not wc -l logs/error_scan
+  # Otherwise variable will have filename, not just number of lines
+  error_len=$(cat logs/error_scan | wc -l)
+  echo $error_len
+  if [ "$error_len" -gt 0 ]
+    then
+      echo $error_len 
+  
+      echo "Errors found while scanning classifiers"
+      ls logs/error_scan
+      exit 1
+  fi
+  
+  if [ -f "$(find "training" -maxdepth 1 -name "tpot_${EXP_PREFIX}.py" | head -1)" ] 
+    then   
+      echo -e "\e[35mClassifiers scanned and tpot parameters found\e[39m)"
+    else
+      echo -e "\e[91mNo output files from classifier scan found (tpot_${EXP_PREFIX}*py)\e[39m)"
+      echo -e "\e[91mExiting\e[39m"
+      exit 1
+  fi
 
-# Remove empty error files (meaning no error)
-# Parallel returns an empty stderr by default
-find "logs" -maxdepth 1 -name "error_scan" -empty -delete
-
-#Look for any errors and report. Error log is cleared out at each run so any new errors are from current run
-
-# Cat to wc -l, not wc -l logs/error_scan
-# Otherwise variable will have filename, not just number of lines
-error_len=$(cat logs/error_scan | wc -l)
-echo $error_len
-if [ "$error_len" -gt 0 ]
-  then
-    echo $error_len 
-
-    echo "Errors found while scanning classifiers
-    ls logs/error_scan
-    exit 1
-fi
-
-if [ -f "$(find "training" -maxdepth 1 -name "tpot_${EXP_PREFIX}.py" | head -1)" ] 
-  then   
-    echo -e "\e[35mClassifiers scanned and tpot parameters found\e[39m)"
-  else
-    echo -e "\e[91mNo output files from classifier scan found (tpot_${EXP_PREFIX}*py)\e[39m)"
-    echo -e "\e[91mExiting\e[39m"
-    exit 1
 fi
diff --git a/scripts/cfmsinfer-score b/scripts/cfmsinfer-score
--- a/scripts/cfmsinfer-score
+++ b/scripts/cfmsinfer-score
@@ -4,34 +4,35 @@ source $CONFIG
 
 echo -e "\e[36m Scoring feature matrix with trained model\e[39m"
 
-rm -f logs/error_predict
-rm -f logs/log_predict
+rm -f logs/error_score
+rm -f logs/log_score
 
-echo "python /project/cmcwhite/github/run_TPOT/tpot_predict.py --datafile feature_matrix/${EXP_PREFIX}_feature_matrix.csv --serialized_model training/tpot_${EXP_PREFIX}_fitted_model.p --outfile training/tpot_${EXP_PREFIX}_scored.txt --id_cols 0"  > records/record_predict.sh
+echo "python /project/cmcwhite/github/run_TPOT/tpot_predict.py --datafile feature_matrix/${EXP_PREFIX}.featmat --serialized_model training/tpot_${EXP_PREFIX}_fitted_model.p --outfile training/tpot_${EXP_PREFIX}_scored.txt --id_cols 0"  > records/record_score.sh
 
+if [ $GEN_COMMANDS_ONLY != "T" ];then
 
-bash records/record_score.sh > logs/log_score 2> logs/error_score
-
-
-# Remove empty error files (meaning no error)
-# Parallel returns an empty stderr by default
-find "logs" -maxdepth 1 -name "error_predict" -empty -delete
-
-#Look for any errors and report. Error log is cleared out at each run so any new errors are from current run
-
-# Doesn't need find, just check if exists TODO
-if [ -f "$(find "logs" -maxdepth 1 -name "error_predict" | head -1)" ]
-      then
-        echo "Errors found while predicting with model"
-        ls logs/error_predict
-        exit 1
-fi
-
-if [ -f "$(find "training" -maxdepth 1 -name "tpot_${EXP_PREFIX}_scored.txt" | head -1)" ] 
-  then   
-    echo -e "\e[35mFeature matrix scored with model\e[39m)"
-  else
-    echo -e "\e[91mNo output scores (expected training/tpot_${EXP_PREFIX}_scored.txt)\e[39m)"
-    echo -e "\e[91mExiting\e[39m"
-    exit 1
+  bash records/record_score.sh > logs/log_score 2> logs/error_score
+  
+  # Remove empty error files (meaning no error)
+  # Parallel returns an empty stderr by default
+  find "logs" -maxdepth 1 -name "error_score" -empty -delete
+  
+  #Look for any errors and report. Error log is cleared out at each run so any new errors are from current run
+  
+  # Doesn't need find, just check if exists TODO
+  if [ -f "$(find "logs" -maxdepth 1 -name "error_score" | head -1)" ]
+        then
+          echo "Errors found while using model to score interactions"
+          ls logs/error_score
+          exit 1
+  fi
+  
+  if [ -f "$(find "training" -maxdepth 1 -name "tpot_${EXP_PREFIX}_scored.txt" | head -1)" ] 
+    then   
+      echo -e "\e[35mFeature matrix scored with model\e[39m)"
+    else
+      echo -e "\e[91mNo output scores (expected training/tpot_${EXP_PREFIX}_scored.txt)\e[39m)"
+      echo -e "\e[91mExiting\e[39m"
+      exit 1
+  fi
 fi
diff --git a/scripts/cfmsinfer-train b/scripts/cfmsinfer-train
--- a/scripts/cfmsinfer-train
+++ b/scripts/cfmsinfer-train
@@ -9,29 +9,31 @@ rm -f logs/log_train
 
 echo "python /project/cmcwhite/github/run_TPOT/train_test_model2.py --training_infile feature_matrix/${EXP_PREFIX}_feature_matrix.labeled1 --exported_pipeline training/tpot_${EXP_PREFIX}.py --id_cols 0 --output_basename training/tpot_${EXP_PREFIX}"  > records/record_train_COMMANDS.sh
 
+if [ $GEN_COMMANDS_ONLY != "T" ];then
 
-bash records/record_train_COMMANDS.sh > logs/log_train 2> logs/error_train
-
-
-# Remove empty error files (meaning no error)
-# Parallel returns an empty stderr by default
-find "logs" -maxdepth 1 -name "error_train" -empty -delete
-
-#Look for any errors and report. Error log is cleared out at each run so any new errors are from current run
-
-# Doesn't need find, just check if exists TODO
-if [ -f "$(find "logs" -maxdepth 1 -name "error_train" | head -1)" ]
-      then
-        echo "Errors found while training model"
-        ls logs/error_train
-        exit 1
-fi
-
-if [ -f "$(find "training" -maxdepth 1 -name "tpot_${EXP_PREFIX}_fitted_model.p" | head -1)" ] 
-  then   
-    echo -e "\e[35mModel trained\e[39m)"
-  else
-    echo -e "\e[91mNo model found (expecting training/tpot_${EXP_PREFIX}_fitted_model.p)\e[39m)"
-    echo -e "\e[91mExiting\e[39m"
-    exit 1
+  bash records/record_train_COMMANDS.sh > logs/log_train 2> logs/error_train
+  
+  
+  # Remove empty error files (meaning no error)
+  # Parallel returns an empty stderr by default
+  find "logs" -maxdepth 1 -name "error_train" -empty -delete
+  
+  #Look for any errors and report. Error log is cleared out at each run so any new errors are from current run
+  
+  # Doesn't need find, just check if exists TODO
+  if [ -f "$(find "logs" -maxdepth 1 -name "error_train" | head -1)" ]
+        then
+          echo "Errors found while training model"
+          ls logs/error_train
+          exit 1
+  fi
+  
+  if [ -f "$(find "training" -maxdepth 1 -name "tpot_${EXP_PREFIX}_fitted_model.p" | head -1)" ] 
+    then   
+      echo -e "\e[35mModel trained\e[39m)"
+    else
+      echo -e "\e[91mNo model found (expecting training/tpot_${EXP_PREFIX}_fitted_model.p)\e[39m)"
+      echo -e "\e[91mExiting\e[39m"
+      exit 1
+  fi
 fi
