Working through error handling

diff --git a/scripts/cfmsinfer-alphabetize b/scripts/cfmsinfer-alphabetize
--- a/scripts/cfmsinfer-alphabetize
+++ b/scripts/cfmsinfer-alphabetize
@@ -12,39 +12,21 @@ if [ $GEN_COMMANDS_ONLY != "T" ];then
 
   cat records/record_alphabetize_COMMANDS.sh | parallel -j30 --joblog logs/alphabetize_jobstatus.log &> logs/alphabetize_commands.log 
   
-  echo -e "\e[34mLogged at logs/alphabetize_commands.log\e[39m"
-  jobswitherrors=`tail -n +2 logs/alphabetize_jobstatus.log | awk -F'\t' '$7 != 0'`
-  echo $jobswitherrors | awk -F' ' '{print $NF}' 
-  
+  echo -e "\e[34mLogged at logs/alphabetize_commands.log, logs/alphabetize_jobstatus.log\e[39m"
 
-
-  #errorcodes=`awk -F'\t' '{print $7}' logs/alphabetize_jobstatus.log | tail -n +2 | grep -v "^0$"`
-  echo $errorcodes
-  errorlen=${#errorcodes}
-  echo $errorlen 
-  # Remove empty error files (meaning no error)
-  # Parallel returns an empty stderr by default
+  # Parallel returns empty stderrs by default, remove them
   find "errors" -maxdepth 1 -name "error_alpha*" -empty -delete
-  
-  
-  #Look for any errors and report. Error log is cleared out at each run so any new errors are from current run
- if [ "$errorlen" -gt 0 ]; then
-    echo "errorfound"
-
-    while read exp
-      do
-        if [ -f "$(find "errors" -maxdepth 1 -name "error_alpha*" | head -1)" ]
-          then
-            echo "Errors found while ordering identifiers of features"
-            ls errors/error_alpha*
-            exit 1
-        fi
-      done < $EXPLIST
+ 
+  # Parse parallel joblog to find nonzero exit codes
+  jobswitherrors=`bash scripts/check_joblog.sh logs/alphabetize_jobstatus.log`
+ 
+  if [ -n "$jobswitherrors" ];then 
+    echo -e "\e[91mErrors found while ordering identifiers of features\e[39m" 
+    echo -e "\e[91mSee error logs at:\e[39m"
+    echo -e `echo $jobswitherrors | sed 's/ /\r/g'`
+    exit 1
+  else
+    echo -e "\e[35mFeature IDs alphabetized (elutions/processed_elutions/*.feat.ordered\e[39m)"
   fi
-  
-  if [ -f "$(find "elutions/processed_elutions" -maxdepth 1 -name "*.feat.ordered" | head -1)" ] 
-  then    
-      echo -e "\e[35mFeature IDs alphabetized (elutions/processed_elutions/*.feat.ordered\e[39m)"
-  fi
-  
+ 
 fi
diff --git a/scripts/cfmsinfer-build b/scripts/cfmsinfer-build
--- a/scripts/cfmsinfer-build
+++ b/scripts/cfmsinfer-build
@@ -35,14 +35,13 @@ if [ $GEN_COMMANDS_ONLY != "T" ];then
 
   bash records/record_build_featmat.sh > logs/log_build_featmat 2> errors/error_build_featmat
   
+  # Check for exit code of command 
+  status=$?
   
-  # Remove empty error log
-  find "errors" -maxdepth 1 -name "error_build_featmat" -empty -delete
-  
-  if [ -f errors/error_build_featmat ]; then
-    ls errors/error_build_featmat
+  if [ ! $status -eq 0 ]; then
     echo -e "\e[91mError while building feature matrix\e[39m"
-    echo -e "\e[91mSee log at errors/error_build_featmat\e[39m"
+    echo -e "\e[91mSee errors at errors/error_build_featmat\e[39m"
+
     exit 1
   else
     echo -e "\e[35mFeature matrix built without errors ($OUTPUT_FILE)\e[39m"
diff --git a/scripts/cfmsinfer-corr b/scripts/cfmsinfer-corr
--- a/scripts/cfmsinfer-corr
+++ b/scripts/cfmsinfer-corr
@@ -36,8 +36,7 @@ fi
 #Code
 
 
-echo -e "\e[36mCreate correlation commands (records/record_corr_commands_gen.sh)\ndefault 5 replications with poisson noise, use up to 100 for final calculation\e[39m"
-
+echo -e "\e[36mCreate correlation commands (records/record_corr_commands_gen.sh)\ndefault 5 replications with poisson noise, use up to 100 for final calculation.\nSet ADD_POISSON_NOISE=F for non-count data such as intensities\e[39m"
 
 bash scripts/make_corr_commands.sh $CONFIG
 
@@ -47,28 +46,20 @@ if [ $GEN_COMMANDS_ONLY != "T" ];then
   
   cat records/record_corr_COMMANDS.sh | parallel -j30 --joblog logs/corr_jobstatus.log &> logs/corr_commands.log
   
-  echo -e "\e[34mLogged at logs/corr_commands.log\e[39m"
-  
-  # Remove empty error files (meaning no error)
-  # Parallel returns an empty stderr by default
-  find "errors" -maxdepth 1 -name "error_corr*" -empty -delete 
-  
-  
-  #Look for any errors and report. Error log is cleared out at each run so any new errors are from current run
-  while read exp
-    do
-      if [ -f "$(find "errors" -maxdepth 1 -name "error_corr*" | head -1)" ]
-        then
-          echo "Errors found during calculation of following features"
-          ls errors/error_corr* 
-          exit 1
-      fi
-    done < $EXPLIST
-  
-  # Not technically necessary to be in if statement, because exit 1 hits before if any errors encountered
-  if [ -f "$(find "elutions/processed_elutions" -maxdepth 1 -name "*.feat" | head -1)" ] 
-  then    
-  
-      echo -e "\e[35mFeatures calculated (elutions/processed_elutions/*.feat)\e[39m"
+  echo -e "\e[34mLogged at logs/corr_commands.log, logs/corr_jobstatus.log\e[39m"
+
+  # Parallel returns empty stderrs by default, remove them
+  find "errors" -maxdepth 1 -name "error_corr*" -empty -delete
+ 
+  # Parse parallel joblog to find nonzero exit codes
+  jobswitherrors=`bash scripts/check_joblog.sh logs/corr_jobstatus.log`
+
+  if [ -n "$jobswitherrors" ];then
+    echo -e "\e[91Errors found during calculation of following features:\e[39m"
+    echo -e "\e[91mSee error logs at:\e[39m"
+    echo -e `echo $jobswitherrors | sed 's/ /\r/g'`
+    exit 1
+  else
+    echo -e "\e[35mFeatures calculated (elutions/processed_elutions/*.feat)\e[39m"
   fi
 fi 
diff --git a/scripts/cfmsinfer-rescale b/scripts/cfmsinfer-rescale
--- a/scripts/cfmsinfer-rescale
+++ b/scripts/cfmsinfer-rescale
@@ -10,30 +10,23 @@ echo -e "\e[32mRun rescale commands for distance feature\e[39m"
 if [ $GEN_COMMANDS_ONLY != "T" ];then
 
   cat records/record_rescale_COMMANDS.sh | parallel -j30 --joblog logs/rescale_status.log  &> logs/rescale_commands.log 
-  
-  # Remove empty error files (meaning no error)
-  # Parallel returns an empty stderr by default
-  # TPOT error logs are not technically empty even if no error occurred
-  find "errors" -maxdepth 1 -name "error_rescale*" -empty -delete
-  
-  #Look for any errors and report. Error log is cleared out at each run so any new errors are from current run
-  while read exp
-    do
-      if [ -f "$(find "errors" -maxdepth 1 -name "error_rescale*" | head -1)" ]
-        then
-          echo "Errors found while inverting scale of distance measures"
-          ls errors/error_rescale*
-          exit 1
-      fi
-    done < $EXPLIST
-  
-  if [ -f "$(find "elutions/processed_elutions" -maxdepth 1 -name "*.feat.rescale.ordered" | head -1)" ] 
-    then   
-      echo -e "\e[35mEuclidean and Bray-Curtis features rescaled (elutions/processed_elutions/*.feat.rescale.ordered\e[39m)"
-    else
-      echo -e "\e[91mNo output files from rescaling distance features were found (elutions/processed_elutions/*.feat.rescale.ordered\e[39m)"
-      echo -e "\e[91mExiting\e[39m"
-      exit 1
-  fi
 
-fi
+   echo -e "\e[34mLogged at logs/corr_commands.log, logs/corr_jobstatus.log\e[39m"
+
+  # Parallel returns empty stderrs by default, remove them
+  find "errors" -maxdepth 1 -name "error_rescale*" -empty -delete
+ 
+  # Parse parallel joblog to find nonzero exit codes
+  jobswitherrors=`bash scripts/check_joblog.sh logs/corr_jobstatus.log`
+
+  if [ -n "$jobswitherrors" ];then
+    echo -e "\e[91Errors found while inverting scale of following distance measures:\e[39m"
+    echo -e "\e[91mSee error logs at:\e[39m"
+    echo -e `echo $jobswitherrors | sed 's/ /\r/g'`
+    exit 1
+  else
+    echo -e "\e[35mEuclidean and Bray-Curtis features rescaled (elutions/processed_elutions/*.feat.rescale.ordered)\e[39m"
+  fi
+fi  
+
+
