Add new error catch style to all scripts

diff --git a/scripts/cfmsinfer-cluster b/scripts/cfmsinfer-cluster
--- a/scripts/cfmsinfer-cluster
+++ b/scripts/cfmsinfer-cluster
@@ -20,19 +20,17 @@ if [ $GEN_COMMANDS_ONLY != "T" ];then
    
   bash records/record_cluster.sh  > logs/log_cluster 2> errors/error_cluster
   
-  
-  # Remove empty error log
-  find "errors" -maxdepth 1 -name "error_cluster" -empty -delete
-  
-  if [ -f errors/error_cluster ]; then
-    ls errors/error_cluster
+
+  # Check for exit code of command
+  status=$?
+
+  if [ ! $status -eq 0 ]; then
     echo -e "\e[91mError while clustering interactions\e[39m"
     echo -e "\e[91mSee stdout log at logs/log_cluster\e[39m"
     echo -e "\e[91mSee error log at errors/error_cluster\e[39m"
     exit 1
   else
     echo -e "\e[35mInteractions clustered without errors (training/tpot_${EXP_PREFIX}_scored_walktrap )\e[39m"
-      
-  fi 
-fi    
-    
+
+  fi
+fi
diff --git a/scripts/cfmsinfer-gold b/scripts/cfmsinfer-gold
--- a/scripts/cfmsinfer-gold
+++ b/scripts/cfmsinfer-gold
@@ -26,6 +26,7 @@ echo "python $PCM_DIR/protein_complex_maps/preprocessing_util/complexes/split_co
 # Alphabetize training and test interactions. 
 
 
+
 echo "for ppi in gold_standards/*ppis.txt
  do
    sed -i 's/\t/ /' \$ppi 
@@ -71,32 +72,28 @@ fi
 
 
 
-
-
 rm -f logs/log_gold_standard
 rm -f errors/error_gold_standard
 
 if [ $GEN_COMMANDS_ONLY != "T" ];then
 
   bash records/record_gold_standard.sh > logs/log_gold_standard 2> errors/error_gold_standard 
-   
-  # Remove empty error log
-  find "errors" -maxdepth 1 -name "error_gold_standard" -empty -delete
-  
-  if [ -f errors/error_gold_standard ]; then
-    ls errors/error_gold_standard
-    echo -e "\e[91mError while building feature matrix\e[39m"
+
+  # Check for exit code of command
+  status=$?
+
+  if [ ! $status -eq 0 ]; then
+    echo -e "\e[91mError while formatting goldstandards\e[39m"
     echo -e "\e[91mSee output log at logs/log_gold_standard\e[39m"
-    echo -e "\e[91mSee error log at errors/error_gold_standard\e[39m"
-  
+    echo -e "\e[91mSee errors at errors/error_gold_standard\e[39m"
     exit 1
   else
+
     echo -e "\e[35mGold standard files made without errors (gold_standards/neg_train.txt, gold_standards/neg_test.txt, gold_standard/pos_train.txt, gold_standards/pos_test.txt)\e[39m"
-  
+
   fi
 fi
-
-
+   
 
 # Make annotation file of which interactions are training and which are test
 
diff --git a/scripts/cfmsinfer-label b/scripts/cfmsinfer-label
--- a/scripts/cfmsinfer-label
+++ b/scripts/cfmsinfer-label
@@ -29,15 +29,13 @@ echo "grep -v ",0.0\$" feature_matrix/${EXP_PREFIX}.featmat.labeled > feature_ma
 if [ $GEN_COMMANDS_ONLY != "T" ];then
   bash records/record_label_featmat.sh  > logs/log_label_featmat 2> errors/error_label_featmat
   
-  
-  # Remove empty error log
-  find "errors" -maxdepth 1 -name "error_label_featmat" -empty -delete
-  
-  if [ -f errors/error_label_featmat ]; then
-    ls errors/error_label_featmat
+  # Check for exit code of command
+  status=$?
+
+  if [ ! $status -eq 0 ]; then 
     echo -e "\e[91mError while building feature matrix\e[39m"
-    echo -e "\e[91mSee stdout log at logs/log_label_featmat\e[39m"
-    echo -e "\e[91mSee error log at errors/error_label_featmat\e[39m"
+    echo -e "\e[91mSee stdout at logs/log_label_featmat\e[39m"
+    echo -e "\e[91mSee errors at errors/error_label_featmat\e[39m"
     exit 1
   else
     echo -e "\e[35mFeature matrix labeled without errors (${EXP_PREFIX}.featmat.labeled)\e[39m"
diff --git a/scripts/cfmsinfer-scan b/scripts/cfmsinfer-scan
--- a/scripts/cfmsinfer-scan
+++ b/scripts/cfmsinfer-scan
@@ -21,35 +21,19 @@ if [ $GEN_COMMANDS_ONLY != "T" ];then
 
   bash records/record_scan.sh > logs/log_scan 2> errors/error_scan
   
+  # Check for exit code of command
+  status=$?
+
   # Temp directories are very large
   rm -r training/*tmp
-  
-  # Remove empty error files (meaning no error)
-  # Parallel returns an empty stderr by default
-  find "errors" -maxdepth 1 -name "error_scan" -empty -delete
-  
-  #Look for any errors and report. Error log is cleared out at each run so any new errors are from current run
-  
-  # Cat to wc -l, not wc -l errors/error_scan
-  # Otherwise variable will have filename, not just number of lines
-  error_len=$(cat errors/error_scan | wc -l)
-  echo $error_len
-  if [ "$error_len" -gt 0 ]
-    then
-      echo $error_len 
-  
-      echo "Errors found while scanning classifiers"
-      ls errors/error_scan
-      exit 1
-  fi
-  
-  if [ -f "$(find "training" -maxdepth 1 -name "tpot_${EXP_PREFIX}.py" | head -1)" ] 
-    then   
-      echo -e "\e[35mClassifiers scanned and tpot parameters found\e[39m)"
-    else
-      echo -e "\e[91mNo output files from classifier scan found (tpot_${EXP_PREFIX}*py)\e[39m)"
-      echo -e "\e[91mExiting\e[39m"
-      exit 1
-  fi
 
+  if [ ! $status -eq 0 ]; then
+
+    echo "Errors found while scanning classifiers"
+    echo -e "\e[91mError while building feature matrix\e[39m"
+    echo -e "\e[91mSee errors at errors/error_build_featmat\e[39m"
+    exit 1
+  else
+    echo -e "\e[35mClassifiers scanned and tpot parameters found\e[39m)"
+  fi
 fi
diff --git a/scripts/cfmsinfer-score b/scripts/cfmsinfer-score
--- a/scripts/cfmsinfer-score
+++ b/scripts/cfmsinfer-score
@@ -12,27 +12,17 @@ echo "python /project/cmcwhite/github/run_TPOT/tpot_predict.py --datafile featur
 if [ $GEN_COMMANDS_ONLY != "T" ];then
 
   bash records/record_score.sh > logs/log_score 2> errors/error_score
-  
-  # Remove empty error files (meaning no error)
-  # Parallel returns an empty stderr by default
-  find "errors" -maxdepth 1 -name "error_score" -empty -delete
-  
-  #Look for any errors and report. Error log is cleared out at each run so any new errors are from current run
-  
-  # Doesn't need find, just check if exists TODO
-  if [ -f "$(find "errors" -maxdepth 1 -name "error_score" | head -1)" ]
-        then
-          echo "Errors found while using model to score interactions"
-          ls errors/error_score
-          exit 1
+
+  # Check for exit code of command
+  status=$?
+
+  if [ ! $status -eq 0 ]; then
+    echo -e "\e[91mErrors found while using model to score interactions\e[39m"
+    echo -e "\e[91mSee stout at errors/error_score\e[39m"
+    echo -e "\e[91mSee errors at errors/error_score\e[39m"
+
+    exit 1
+  else
+    echo -e "\e[35mInteractions scored (training/tpot_${EXP_PREFIX}_scored.txt)\e[39m"
   fi
-  
-  if [ -f "$(find "training" -maxdepth 1 -name "tpot_${EXP_PREFIX}_scored.txt" | head -1)" ] 
-    then   
-      echo -e "\e[35mFeature matrix scored with model\e[39m)"
-    else
-      echo -e "\e[91mNo output scores (expected training/tpot_${EXP_PREFIX}_scored.txt)\e[39m)"
-      echo -e "\e[91mExiting\e[39m"
-      exit 1
-  fi
-fi
+fi 
diff --git a/scripts/cfmsinfer-train b/scripts/cfmsinfer-train
--- a/scripts/cfmsinfer-train
+++ b/scripts/cfmsinfer-train
@@ -12,28 +12,18 @@ echo "python /project/cmcwhite/github/run_TPOT/train_test_model2.py --training_i
 if [ $GEN_COMMANDS_ONLY != "T" ];then
 
   bash records/record_train_COMMANDS.sh > logs/log_train 2> errors/error_train
-  
-  
-  # Remove empty error files (meaning no error)
-  # Parallel returns an empty stderr by default
-  find "errors" -maxdepth 1 -name "error_train" -empty -delete
-  
-  #Look for any errors and report. Error log is cleared out at each run so any new errors are from current run
-  
-  # Doesn't need find, just check if exists TODO
-  if [ -f "$(find "errors" -maxdepth 1 -name "error_train" | head -1)" ]
-        then
-          echo "Errors found while training model"
-          ls errors/error_train
-          exit 1
+
+  # Check for exit code of command
+  status=$?
+
+  if [ ! $status -eq 0 ]; then
+    echo -e "\e[91mError while training model\e[39m"
+    echo -e "\e[91mSee stdout at log/log_train\e[39m"
+    echo -e "\e[91mSee errors at errors/error_train\e[39m"
+    exit 1
+  else
+    echo -e "\e[35mModel trained without errors (tpot_${EXP_PREFIX}_fitted_model.p)\e[39m"
+
   fi
-  
-  if [ -f "$(find "training" -maxdepth 1 -name "tpot_${EXP_PREFIX}_fitted_model.p" | head -1)" ] 
-    then   
-      echo -e "\e[35mModel trained\e[39m)"
-    else
-      echo -e "\e[91mNo model found (expecting training/tpot_${EXP_PREFIX}_fitted_model.p)\e[39m)"
-      echo -e "\e[91mExiting\e[39m"
-      exit 1
-  fi
-fi
+fi  
+ 
